PJK-462.Add check (allow start branches only with `fb-` prefix)

diff --git a/git-flow-feature b/git-flow-feature
--- a/git-flow-feature
+++ b/git-flow-feature
@@ -1,4 +1,5 @@
-#
+
+
 # git-flow -- A collection of Git extensions to provide high-level
 # repository operations for Vincent Driessen's branching model.
 #
@@ -197,8 +198,18 @@ cmd_start() {
 	DEFINE_boolean fetch false 'fetch from origin before performing local operation' F
 	parse_args "$@"
 	BASE=${2:-$DEVELOP_BRANCH}
+	
 	require_name_arg
 
+	PREFIX=`expr substr $NAME 1 3`
+	echo "Prefix of the branch: '$PREFIX'"
+	if [ "$PREFIX" != "fb-" ]; then
+                warn "Missing preifx fb-"
+                echo "Must create branch with prefix fb-"
+                exit 1
+        fi
+
+		 	
 	# sanity checks
 	require_branch_absent "$BRANCH"
 
