Implement function check naming convention

diff --git a/gitflow-common b/gitflow-common
--- a/gitflow-common
+++ b/gitflow-common
@@ -318,13 +318,24 @@ require_branches_equal() {
 }
 
 check_naming_conventions() {
-    if [ -f $HOME/.gitflow ]; then
+    fname="/etc/gitflow.conf"
+    if [ -f $fname ]; then
         echo "Try to run checking name conventions using config file"
         
-        if ! startswith "$1" "fb-"; then
-            warn "Missing preifx fb-"
-            echo "Must create branch with prefix fb-"
-            exit 1
-        fi
+        exec<$fname
+        while read line
+        do       
+            if echo $line | grep -qE '='; then
+                param=$(echo $line|awk -F '=' '{print $1}'|awk '{print $1}')
+                if [ "$param" = "gitflow.fb.naming.convention" ]; then
+                    value=$(echo $line|awk -F '=' '{print $2}'|awk '{print $1}' )                    
+                    if ! startswith "$1" $value; then
+                        warn "Missing preifx $value"
+                        echo "Must create branch with prefix $value"
+                        exit 1
+                    fi
+                fi
+            fi          
+        done
     fi    
  }
