Introduce check_naming_conventions function

diff --git a/gitflow-common b/gitflow-common
--- a/gitflow-common
+++ b/gitflow-common
@@ -316,3 +316,15 @@ require_branches_equal() {
 		fi
 	fi
 }
+
+check_naming_conventions() {
+    if [ -f $HOME/.gitflow ]; then
+        echo "Try to run checking name conventions using config file"
+        
+        if ! startswith "$1" "fb-"; then
+            warn "Missing preifx fb-"
+            echo "Must create branch with prefix fb-"
+            exit 1
+        fi
+    fi    
+ }
